name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "2 4 * * *"
  push:
    branches:
      - main

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build landingpage
        run: |
          mkdir dist
          cp index.html ./dist/index.html
          touch ./dist/.nojekyll
          echo "bennyse.de" > ./dist/CNAME
      - name: Deploy landingpage
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
