name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: install dependencies
        run: npm ci
      - name: Build landingpage
        run: |
          npm run build
          touch ./dist/.nojekyll
          echo "bennyse.de" > ./dist/CNAME
      - name: Deploy landingpage
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
